version: "3.9"

services:
  langflow:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      LANGFLOW_SUPERUSER: "${LANGFLOW_SUPERUSER}"
      LANGFLOW_SUPERUSER_PASSWORD: "${LANGFLOW_SUPERUSER_PASSWORD}"
      BACKEND_URL: "${BACKEND_URL}"
      LANGFLOW_AUTO_LOGIN: "${LANGFLOW_AUTO_LOGIN}"
      LANGFLOW_CACHE_TYPE: "${LANGFLOW_CACHE_TYPE}"
      LANGFLOW_CONFIG_DIR: "${LANGFLOW_CONFIG_DIR}"
      LANGFLOW_DATABASE_URL: "${LANGFLOW_DATABASE_URL}"
      LANGFLOW_ENV: "${LANGFLOW_ENV}"
      LANGFLOW_HOST: "${LANGFLOW_HOST}"
      LANGFLOW_LANGCHAIN_CACHE: "${LANGFLOW_LANGCHAIN_CACHE}"
      LANGFLOW_LOG_LEVEL: "${LANGFLOW_LOG_LEVEL}"
      LANGFLOW_LOG_FILE: "${LANGFLOW_LOG_FILE}"
      LANGFLOW_OPEN_BROWSER: "${LANGFLOW_OPEN_BROWSER}"
      LANGFLOW_PORT: "${LANGFLOW_PORT}"
      LANGFLOW_REDIS_CACHE_EXPIRE: "${LANGFLOW_REDIS_CACHE_EXPIRE}"
      LANGFLOW_REDIS_HOST: "${LANGFLOW_REDIS_HOST}"
      LANGFLOW_REDIS_PORT: "${LANGFLOW_REDIS_PORT}"
      LANGFLOW_REDIS_DB: "${LANGFLOW_REDIS_DB}"
      LANGFLOW_REMOVE_API_KEYS: "${LANGFLOW_REMOVE_API_KEYS}"
      LANGFLOW_SAVE_DB_IN_CONFIG_DIR: "${LANGFLOW_SAVE_DB_IN_CONFIG_DIR}"
      LANGFLOW_STORE_ENVIRONMENT_VARIABLES: "${LANGFLOW_STORE_ENVIRONMENT_VARIABLES}"
      LANGFLOW_WORKERS: "${LANGFLOW_WORKERS}"
