services:
  langflow:
    image: ghcr.io/aluhning/nearflow:latest
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"         # Maximum size of each log file before it is rotated (e.g., 50 MB)
        max-file: "3"           # Number of log files to keep before older ones are removed
    volumes:
      - ./data:/app/.langflow
    depends_on:
      - postgres
      - redis
    networks:
      - langflow-net

  postgres:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - langflow-net

  redis:
    image: redis:alpine
    restart: unless-stopped
    env_file: .env
    networks:
      - langflow-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - langflow
    networks:
      - langflow-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
             --email a.luhning@vitalpoint.ai --agree-tos --no-eff-email
             -d ai.vitalpoint.ai"

volumes:
  pgdata:

networks:
  langflow-net:
